version: '3'
services:
  laravel:
    build: .
    image: leejoneshane/laravel
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:80
      - 5173:5173
    environment:
      DOMAIN: www.your.com
      MAIL: leejoneshane@gmail.com
      WEB_PASSWORD: 123456
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 123456
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: client_host=host.docker.internal
      MEILISEARCH_HOST: http://melisearch:7700
      MEILISEARCH_KEY: masterKey
    volumes:
      - www:/var/www/html
    networks:
      - backend
    depends_on:
      - mysql
      - redis
      - meilisearch
      - mailhog
      
  redis:
    image: redis
    networks:
      - backend
      
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700
    environment:
      MEILI_MASTER_KEY: masterKey
      MEILI_ENV: production
    volumes:
      - www:/meili_data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
      retries: 3
      timeout: 5s
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - backend
      
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  www:
